import streamlit as st
# Page Configuration
st.set_page_config(
    page_title="Version Comparison",
    page_icon="🔀",
    layout="wide"
)
st.title("PragyanAI - Multi-Agent Version Selector & Comparison Menu")
st.markdown(
    "Compare the evolution of your Verilog code across different stages of the multi-agent pipeline: "
    "from the initial raw draft generated by the **Generator Agent**, through the **Critic Agent** audit notes, "
    "to the final **Verified Production Version**."
)
# -----------------------------------------------------------------------------
# Check Session State Data Availability
# -----------------------------------------------------------------------------
has_data = any([
    st.session_state.get("rtl_v1"),
    st.session_state.get("rtl_critic_notes"),
    st.session_state.get("rtl_final")
])
if not has_data:
    st.warning(" No pipeline execution history found in session state. Please run the **Multi-Agent Pipeline** first to generate code artifacts.")
    if st.button("👉 Go to Multi-Agent Pipeline"):
        st.switch_page("pages/1_🤖_Multi_Agent_Pipeline.py")
    st.stop()
# -----------------------------------------------------------------------------
# View Layout Selection
# -----------------------------------------------------------------------------
comparison_mode = st.radio(
    "Choose Comparison View:",
    ["Single Version Inspector", "Side-by-Side Version Comparison"],
    horizontal=True
)
st.markdown("---")
# -----------------------------------------------------------------------------
# Mode 1: Single Version Inspector
# -----------------------------------------------------------------------------
if comparison_mode == "Single Version Inspector":
    version_choice = st.selectbox(
        "Select Agent Version to Review:",
        [
            "Initial Generator Version (v1)", 
            "Critic Agent Audit Notes", 
            "Final Verified Production Version"
        ]
    )
    if version_choice == "Initial Generator Version (v1)":
        st.subheader(" Initial Generator Agent Draft")
        v1_code = st.session_state.get("rtl_v1", "// No initial draft available.")
        st.code(v1_code, language="verilog")
    elif version_choice == "Critic Agent Audit Notes":
        st.subheader(" Critic Agent Audit & Recommendations")
        critic_notes = st.session_state.get("rtl_critic_notes", "*No critic notes recorded.*")
        st.markdown(critic_notes)
    elif version_choice == "Final Verified Production Version":
        st.subheader(" Final Verified Production RTL")
        final_code = st.session_state.get("rtl_final", "// No final code available.")
        st.code(final_code, language="verilog")
# -----------------------------------------------------------------------------
# Mode 2: Side-by-Side Comparison
# -----------------------------------------------------------------------------
else:
    st.subheader(" Side-by-Side Version Comparison (Initial vs Final)")
    col_v1, col_v_final = st.columns(2)
    with col_v1:
        st.markdown("####  Initial Generator Draft (v1)")
        v1_code = st.session_state.get("rtl_v1", "// N/A")
        st.code(v1_code, language="verilog") 
    with col_v_final:
        st.markdown("####  Final Verified Version")
        final_code = st.session_state.get("rtl_final", "// N/A")
        st.code(final_code, language="verilog") 
    st.markdown("---")
    st.subheader(" Critic Feedback Summary")
    critic_notes = st.session_state.get("rtl_critic_notes", "*No critic notes available.*")
    st.markdown(critic_notes)
